./add-package add ~/CLionProjects/cstr-functions/cstr-functions-*.pkg.tar.zst
./add-package add ~/qtprojects/display-menu/display-menu-*.pkg.tar.zst
./add-package add ~/CLionProjects/fish-completions/fish-completions-*.pkg.tar.zst
./add-package add ~/CLionProjects/inet-comm/inet-comm-*.pkg.tar.zst
./add-package add ~/CLionProjects/kazkueme/kazkueme-*.pkg.tar.zst
./add-package add ~/CLionProjects/level_editor/level-config-*.pkg.tar.zst
./add-package add ~/CLionProjects/level_editor/editor_pkg/level-editor-*.pkg.tar.zst
./add-package add ~/CLionProjects/log-console/log-console-*.pkg.tar.zst
./add-package add ~/CLionProjects/lyricsinject/lyricsinject-*.pkg.tar.zst
./add-package add ~/CLionProjects/sfml_triangle/sfml-triangle-5:2-2-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/xor-crypto/xor-crypto-*.pkg.tar.zst
./add-package add ~/CLionProjects/xor-crypto-token/xor-crypto-token-*.pkg.tar.zst
./add-package add ~/qtprojects/kazkueme-qt/kazkueme-qt-*.pkg.tar.zst
./add-package add ~/CLionProjects/parse-arguments/parse-arguments-*.pkg.tar.zst
./add-package add ~/CLionProjects/neuro/neuro-*.pkg.tar.zst
./add-package add ~/CLionProjects/password-query/password-query-*.pkg.tar.zst
./add-package add ~/CLionProjects/system-actions-logger/system-action-logger-*.pkg.tar.zst
./add-package add ~/CLionProjects/timing/timing-*.pkg.tar.zst
./add-package add ~/CLionProjects/xor-crypto-lib/xor-crypto-lib-*.pkg.tar.zst
./add-package add ~/CLionProjects/kazkueme-comm/kazkueme-comm-*.pkg.tar.zst
./add-package add ~/CLionProjects/simplify-expr/simplify-expr-*.pkg.tar.zst
./add-package add ~/CLionProjects/expression-converter/expression-converter-*.pkg.tar.zst
./add-package add ~/CLionProjects/cppjava_bench/cppjava-bench-*.pkg.tar.zst
./add-package add ~/CLionProjects/kazkueme-client/kazkueme-client-*.pkg.tar.zst
./add-package add ~/CLionProjects/cppjava_bench/cppjava-bench-1:3-0-x86_64.pkg.tar.zst

