./add-package add ~/CLionProjects/cstr-functions/cstr-functions-*-x86_64.pkg.tar.zst
./add-package add ~/qtprojects/display-menu/display-menu-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/fish-completions/fish-completions-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/inet-comm/inet-comm-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/kazkueme/kazkueme-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/level_editor/level-config-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/level_editor/editor_pkg/level-editor-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/log-console/log-console-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/lyricsinject/lyricsinject-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/sfml_triangle/sfml-triangle-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/xor-crypto/xor-crypto-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/xor-crypto-token/xor-crypto-token-*-x86_64.pkg.tar.zst
./add-package add ~/qtprojects/kazkueme-qt/kazkueme-qt-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/parse-arguments/parse-arguments-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/neuro/neuro-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/password-query/password-query-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/system-actions-logger/system-action-logger-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/timing/timing-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/xor-crypto-lib/xor-crypto-lib-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/kazkueme-comm/kazkueme-comm-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/simplify-expr/simplify-expr-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/expression-converter/expression-converter-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/cppjava_bench/cppjava-bench-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/kazkueme-client/kazkueme-client-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/ruled-object/ruled-object-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/execute-process-linux/execute-process-linux-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/linux-file-server-comm/linux-file-server-comm-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/linux-file-server-server/linux-file-server-server-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/linux-file-server-client/linux-file-server-client-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/linux-file-server-client-qt/linux-file-server-client-qt-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/linear-vector/linear-vector-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/dws/dws-*-x86_64.pkg.tar.zst
./add-package add ~/CLionProjects/port_flooder/port-flooder-*-x86_64.pkg.tar.zst
